### PR TITLE
Add annotation for return value of Rule::getOptions()

### PR DESCRIPTION
**Pull request by Sergiayn**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | #225

I didn't add annotation for this

```php
public function getOptions(): array
{
    $arrayOfRules = [];
    foreach ($this->rules as $rule) {
        if ($rule instanceof SerializableRuleInterface) {
            $arrayOfRules[] = array_merge([$rule->getName()], $rule->getOptions());
        } else {
            $arrayOfRules[] = [$rule->getName()];
        }
    }
    return $arrayOfRules;
}
```

### CODE REVIEW

**Review by xepozz — CHANGES_REQUESTED** [review]
It's useless because if you need to dump rules from a form/dto you need to use https://github.com/yiisoft/validator/blob/master/src/RulesDumper.php that will provide a lot of different information that you may use.

If you want to use `getOptions()` directly tell us the reason.

**Comment by samdark** [comment]
@xepozz he's not using getOptions. This PR is about annotations.

**Comment by xepozz** [comment]
I see. And why?
Nothing changed except added a need to change code twice. It's like to have both an annotation and a type for object.

**Comment by arogachev** [comment]
Sorry, we decided to not add it for now. See https://github.com/yiisoft/validator/issues/225#issuecomment-1202088142 for explanation.

**Pull request closed without merging**
