### PR TITLE
Add optional rule

### PR DESCRIPTION
**Pull request by vjik**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | -

Based on https://github.com/yiisoft/validator/pull/102

### CODE REVIEW

**Comment by samdark** [comment]
The concept of making everything required while having optional rule doesn't fit common forms pattern which is "everything is optional unless required". The pattern is used in [HTML5 client-side validation](https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation#using_built-in_form_validation). Going against it would cause pain.

**Comment by arogachev** [comment]
What's the current status of this PR?

**Comment by arogachev** [comment]
Is it somehow related to #132?

**Comment by samdark** [comment]
Related https://github.com/yiisoft/validator/issues/213

**Pull request closed without merging**
