### PR TITLE
Rule::skipOnEmpty() -> Rule::withSkipOnEmpty()

### PR DESCRIPTION
**Pull request by kamarton**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ✔️
| Tests pass?   | ✔️
| Fixed issues  | -

### CODE REVIEW

**Comment by samdark** [comment]
I'm not sure about that. Rules are used extensively in the code with many sequential calls:

```php
(new Number())->min(10)->integer()->skipOnEmpty(true);
```

If we're going to rename all the methods to have `with` prefix, that would become:

```php
(new Number())->withMin(10)->withInteger()->withSkipOnEmpty(true);
```

**Comment by kamarton** [comment]
> I'm not sure about that. Rules are used extensively in the code with many sequential calls:
> 
> ```php
> (new Number())->min(10)->integer()->skipOnEmpty(true);
> ```

`min()` and `integer` not clone the object.

Two option:
1. add `with` prefix (this PR)
2. remove object clone

**Comment by samdark** [comment]
> min() and integer not clone the object.

They should.

**Comment by kamarton** [comment]
> They should.

If cloning is needed, then the `with` prefix should be used.

https://github.com/yiisoft/validator/blob/4b54c97e9b0c0c7b68e1c253779ae40c43ace1b0/src/Rule/Number.php#L75-L85

https://github.com/yiisoft/validator/blob/4b54c97e9b0c0c7b68e1c253779ae40c43ace1b0/src/Rule/HasLength.php#L68-L78

...

**Comment by samdark** [comment]
@kamarton `with` prefix will kill readability.

**Comment by kamarton** [comment]
> @kamarton `with` prefix will kill readability.

Currently the method name and hence the usage is inconsistent. `SkipOnEmpty()` returns a new clone (this is already contrary to the `with` prefix used in PSR interfaces). However, the `Number::min()` (and all other Rule methods) method no longer returns a clone.

Whether or not a new clone is needed is a different matter than when the method names do not follow regularity...

**Comment by samdark** [comment]
See https://github.com/yiisoft/validator/pull/61

**Pull request closed without merging**
