### PR TITLE
Rename `Coordinate` class in tests

### PR DESCRIPTION
**Pull request by arogachev**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌

### CODE REVIEW

**Comment by vjik** [comment]
Run CI actions, please.

**Review by samdark — CHANGES_REQUESTED** [review]
Previous name is correct.

**Comment by arogachev** [comment]
@samdark

- x or y - coordinate;
- x and y - coordinates.

**Comment by arogachev** [comment]
@vjik :heavy_check_mark:

**Review by samdark — APPROVED** [review]

**Review by vjik — APPROVED** [review]

**Pull request merged**
