### PR TITLE
Fix #252: Do not extend RulesProviderInterface from DataSetInterface

### LINKED ISSUE #252: Do not extend RulesProviderInterface from DataSetInterface
Make these two independent interfaces.

### PR DESCRIPTION
**Pull request by samdark**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ✔️
| Fixed issues  | #252

### CODE REVIEW

**Comment by xepozz** [comment]
Also need to adjust changes in `demo` and maybe in `form` too.

**Review by xepozz — APPROVED** [review]

**Review by rustamwin — APPROVED** [review]
Need to check dependent packages (request-model, form)

**Comment by samdark** [comment]
- [ ] form
- [ ] request-model
- [ ] demo-api
- [ ] app-api

**Comment by samdark** [comment]
Checked other packages. No changes are needed.

**Pull request merged**
