### PR TITLE
Add strict mode to number rule

### PR DESCRIPTION
**Pull request by rustamwin**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️/❌
| Breaks BC?    | ❌
| Fixed issues  | #118

### CODE REVIEW

**Comment by vjik** [comment]
Maybe don't add option "strict", but make the number rule is always strict?
Has use cases, when number rule should accept boolean values?

**Comment by samdark** [comment]
I don't have any. @rustamwin?

**Comment by rustamwin** [comment]
I don't have too.

**Review by vjik — APPROVED** [review]

**Comment by samdark** [comment]
👍

**Pull request merged**
